apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: my-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      name: my-deploy
      labels:
        app: my-deploy
    spec:
      containers:
        - name: my-deploy
          resources:
            requests:
              cpu: 200m
              memory: 10Mi
          image: tsarankouviachaslau/kuber-demo:4.0.0
          ports:
            - containerPort: 8081

