apiVersion: apps/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: http://localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-svc
              servicePort: 81