apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: hello-service
              servicePort: 8081