apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-deploy
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: argo.application
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-deploy
                port:
                  number: 8080