apiVersion: v1
kind: Service
metadata:
  name: my-deploy
spec:
  selector:
    app: my-deploy
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30003
      targetPort: 8081
  type: NodePort